---
name: tests

on:
  push:
    branches: [ master ]
  pull_request:
  schedule:
    - cron: '0 0 * * WED,SAT' # 00:00 on Wednesdays and Saturdays, weekly.

jobs:
  up-to-date:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v4

    - name: Install Dependencies via Yarn
      run: |
        rm -rf node_modules
        yarn install --frozen-lockfile

    - name: Install Dependencies via NPM
      run: |
        rm -rf node_modules
        npm ci

  fmt:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v4

    - name: Install Dependencies
      run: npm ci

    - name: Run ESLint Check
      run: npx eslint .

  linter:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v4
      with:
        # Full git history is needed to get a proper list of changed files within `super-linter`
        fetch-depth: 0

    - name: Install Dependencies
      run: npm ci

    - name: Lint Code Base
      uses: github/super-linter@v5
      env:
        VALIDATE_ALL_CODEBASE: false
        DEFAULT_BRANCH: master
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

        JSCPD_CONFIG_FILE: .jscpd.json
        GITLEAKS_CONFIG_FILE: .gitleaks.toml
        VALIDATE_JAVASCRIPT_ES: false
        VALIDATE_JAVASCRIPT_STANDARD: false
